import React, { useState, useEffect, useRef } from 'react';
import { Routes, Route, useNavigate } from 'react-router-dom';
import { NotesPage } from '../features/notes/pages/NotesPage';
import { NotePage } from '../features/notes/pages/NotePage';
import { SidePanelPage } from '../features/notes/pages/SidePanelPage';
import { MainLayout } from '../components/layout/MainLayout';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Spinner } from '../components/ui/Spinner';
import { QUICK_ACTIONS } from '../constants';
import { Note, NoteSettings } from '../features/notes/types/notes.types';
import { notesApi } from '../features/notes/api/notes.api';
import { parseMarkdownToHtml } from '../lib/markdown';
import { GenerationErrorAlert } from '../features/notes/components/GenerationErrorAlert';

const HomePage: React.FC = () => {
  const [youtubeUrl, setYoutubeUrl] = useState('');
  const [customPrompt, setCustomPrompt] = useState('');
  const [customTopic, setCustomTopic] = useState('');
  const [showSettings, setShowSettings] = useState(true);
  const [detectedVideo, setDetectedVideo] = useState<{ id: string; title: string; channel?: string; thumbnail?: string } | null>(null);

  // Settings Sliders State
  const [detailLevel, setDetailLevel] = useState<'summary' | 'detailed' | 'comprehensive'>('detailed');
  const [diagramDensity, setDiagramDensity] = useState<'none' | 'balanced' | 'heavy'>('balanced');
  const [examples, setExamples] = useState<'concise' | 'many'>('many');
  const [includeCode, setIncludeCode] = useState(true);
  const [detailedMath, setDetailedMath] = useState(true);

  const navigate = useNavigate();
  const autoGeneratedRef = useRef(false);

  const runSynthesis = (url: string, topic?: string, prompt?: string) => {
    if (!url.trim()) return;

    const newNoteId = `note-${Date.now()}`;
    const settings: NoteSettings = {
      detailLevel,
      diagramDensity,
      examples,
      includeCode,
      detailedMath,
    };

    const topicTitle = topic || customTopic || 'Synthesized Academic Notes';

    const pendingDraft = {
      id: newNoteId,
      youtubeUrl: url.trim(),
      customTopic: topicTitle,
      customPrompt: prompt || customPrompt || '',
      settings,
    };

    sessionStorage.setItem(`pending_note_gen_${newNoteId}`, JSON.stringify(pendingDraft));
    localStorage.setItem(`pending_note_gen_${newNoteId}`, JSON.stringify(pendingDraft));
    navigate(`/notes/${newNoteId}?streaming=1`);
  };

  // Auto-detect video when redirected from the Chrome extension button or query params
  useEffect(() => {
    // 1. Check URL query params
    const searchParams = new URLSearchParams(window.location.search);
    const hashQuery = window.location.hash.includes('?') ? window.location.hash.split('?')[1] : '';
    const hashParams = new URLSearchParams(hashQuery);
    
    const videoId = searchParams.get('v') || hashParams.get('v');
    const videoTitle = searchParams.get('title') || hashParams.get('title');
    const draftParam = searchParams.get('draft') || hashParams.get('draft');
    const shouldAuto = searchParams.get('auto') === '1' || hashParams.get('auto') === '1';

    if (draftParam && !autoGeneratedRef.current) {
      try {
        const raw = decodeURIComponent(atob(decodeURIComponent(draftParam)));
        const draftData = JSON.parse(raw);
        if (draftData && draftData.id) {
          autoGeneratedRef.current = true;
          sessionStorage.setItem(`pending_note_gen_${draftData.id}`, JSON.stringify(draftData));
          navigate(`/notes/${draftData.id}?streaming=1`, { replace: true });
          return;
        }
      } catch (e) {
        console.warn('Failed to parse draft from extension:', e);
      }
    }

    if (videoId) {
      const fullUrl = `https://www.youtube.com/watch?v=${videoId}`;
      setYoutubeUrl(fullUrl);
      if (videoTitle) setCustomTopic(videoTitle);
      setDetectedVideo({
        id: videoId,
        title: videoTitle || `YouTube Video (${videoId})`,
        thumbnail: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
      });

      if (shouldAuto && !autoGeneratedRef.current) {
        autoGeneratedRef.current = true;
        runSynthesis(fullUrl, videoTitle || undefined);
      }
      return;
    }

    // 2. Check chrome.storage.local from extension content script
    if (typeof chrome !== 'undefined' && chrome.storage?.local) {
      chrome.storage.local.get(['currentVideo'], (result: { [key: string]: any }) => {
        const v = result.currentVideo as { id: string; title: string; channel?: string; thumbnail?: string } | undefined;
        if (v && v.id) {
          const fullUrl = `https://www.youtube.com/watch?v=${v.id}`;
          setYoutubeUrl(fullUrl);
          if (v.title) setCustomTopic(v.title);
          setDetectedVideo(v);
        }
      });
    }
  }, []);

  const handleGenerate = (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    runSynthesis(youtubeUrl, customTopic, customPrompt);
  };

  const handlePresetClick = (presetTopic: string) => {
    setCustomTopic(presetTopic);
  };

  return (
    <MainLayout showSidebar>
      <div className="max-w-4xl mx-auto px-4 py-10">
        <div className="text-center mb-8">
          <div className="inline-block px-3 py-1 bg-amber-100/80 text-amber-900 border border-amber-300/80 rounded-full text-xs font-mono font-semibold uppercase tracking-wider mb-3">
            Academic Transcript Synthesizer
          </div>
          <h1 className="font-serif font-bold text-4xl text-stone-900 tracking-tight sm:text-5xl mb-3">
            Convert Video Lectures into Clean Academic Notes
          </h1>
          <p className="text-base text-stone-600 max-w-2xl mx-auto leading-relaxed">
            Generate standalone, whitepaper-styled A4 PDF notes featuring embedded vector diagrams, equations, callouts, and clean typographic tables.
          </p>
        </div>

        <form onSubmit={handleGenerate} className="bg-amber-50/70 border border-amber-200/80 p-8 rounded-2xl shadow-sm space-y-6">
          {detectedVideo && (
            <div className="bg-white/95 border border-amber-300/90 rounded-xl p-4 flex items-center justify-between gap-4 shadow-xs">
              <div className="flex items-center gap-4 min-w-0">
                {detectedVideo.thumbnail && (
                  <img
                    src={detectedVideo.thumbnail}
                    alt={detectedVideo.title}
                    className="w-20 h-14 object-cover rounded-lg shadow-inner border border-stone-200 flex-shrink-0"
                  />
                )}
                <div className="min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-amber-100 text-amber-900 border border-amber-200 uppercase">
                      Detected Active YouTube Video
                    </span>
                    {detectedVideo.channel && (
                      <span className="text-xs text-stone-500 truncate">{detectedVideo.channel}</span>
                    )}
                  </div>
                  <h4 className="text-sm font-semibold text-stone-900 truncate font-serif">
                    {detectedVideo.title}
                  </h4>
                </div>
              </div>
              <Button
                type="button"
                variant="primary"
                size="sm"
                onClick={() => runSynthesis(`https://www.youtube.com/watch?v=${detectedVideo.id}`, detectedVideo.title)}
                className="whitespace-nowrap flex-shrink-0 cursor-pointer"
              >
                Synthesize Now
              </Button>
            </div>
          )}

          <Input
            label="YouTube Video Link"
            type="url"
            placeholder="https://www.youtube.com/watch?v=..."
            value={youtubeUrl}
            onChange={(e) => setYoutubeUrl(e.target.value)}
            required
            helperText="Supports technical masterclasses, lecture recordings, and architecture breakdowns."
          />

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <Input
              label="Topic / Subject Title (Optional)"
              type="text"
              placeholder="e.g. Distributed Consensus & Raft Protocol"
              value={customTopic}
              onChange={(e) => setCustomTopic(e.target.value)}
            />
            <Input
              label="Custom AI Focus Prompt (Optional)"
              type="text"
              placeholder="e.g. Focus on code samples & state diagrams"
              value={customPrompt}
              onChange={(e) => setCustomPrompt(e.target.value)}
            />
          </div>

          {/* Quick Topic Presets */}
          <div>
            <p className="text-xs font-mono text-stone-500 mb-2 font-medium">Quick Topic Recipes:</p>
            <div className="flex flex-wrap gap-2">
              {QUICK_ACTIONS.map((action) => (
                <button
                  key={action.id}
                  type="button"
                  onClick={() => handlePresetClick(action.label)}
                  className="px-3 py-1 bg-white hover:bg-amber-100/60 border border-amber-200 text-stone-700 hover:text-stone-900 text-xs rounded-lg transition-colors font-medium cursor-pointer"
                >
                  {action.label}
                </button>
              ))}
            </div>
          </div>

          {/* Settings Sliders Panel */}
          <div className="border-t border-amber-200/80 pt-5">
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-serif font-bold text-base text-stone-900 flex items-center gap-2">
                ⚙️ Synthesis Detail & Diagram Settings
              </h3>
              <button
                type="button"
                onClick={() => setShowSettings(!showSettings)}
                className="text-xs font-mono text-amber-800 hover:underline cursor-pointer"
              >
                {showSettings ? 'Hide Sliders' : 'Customize Sliders'}
              </button>
            </div>

            {showSettings && (
              <div className="space-y-5 bg-white/80 p-5 rounded-xl border border-amber-200/60">
                {/* 1. Detail Level Selector */}
                <div>
                  <div className="flex justify-between items-center mb-1">
                    <label className="text-xs font-semibold uppercase tracking-wider text-stone-700">
                      Depth & Detail Level
                    </label>
                    <span className="text-xs font-mono text-amber-800 font-bold uppercase">{detailLevel}</span>
                  </div>
                  <div className="grid grid-cols-3 gap-2">
                    {(['summary', 'detailed', 'comprehensive'] as const).map((lvl) => (
                      <button
                        key={lvl}
                        type="button"
                        onClick={() => setDetailLevel(lvl)}
                        className={`py-2 px-3 text-xs font-medium rounded-lg border transition-all capitalize cursor-pointer ${
                          detailLevel === lvl
                            ? 'bg-amber-700 text-white border-amber-800 shadow-sm font-semibold'
                            : 'bg-stone-50 text-stone-700 border-stone-200 hover:bg-stone-100'
                        }`}
                      >
                        {lvl}
                      </button>
                    ))}
                  </div>
                </div>

                {/* 2. Diagram Density Selector */}
                <div>
                  <div className="flex justify-between items-center mb-1">
                    <label className="text-xs font-semibold uppercase tracking-wider text-stone-700">
                      Diagram & Flowchart Density
                    </label>
                    <span className="text-xs font-mono text-amber-800 font-bold uppercase">{diagramDensity}</span>
                  </div>
                  <div className="grid grid-cols-3 gap-2">
                    {(['none', 'balanced', 'heavy'] as const).map((density) => (
                      <button
                        key={density}
                        type="button"
                        onClick={() => setDiagramDensity(density)}
                        className={`py-2 px-3 text-xs font-medium rounded-lg border transition-all capitalize cursor-pointer ${
                          diagramDensity === density
                            ? 'bg-amber-700 text-white border-amber-800 shadow-sm font-semibold'
                            : 'bg-stone-50 text-stone-700 border-stone-200 hover:bg-stone-100'
                        }`}
                      >
                        {density === 'none' ? 'Minimal' : density === 'balanced' ? 'Balanced' : 'Heavy Architecture'}
                      </button>
                    ))}
                  </div>
                </div>

                {/* 3. Worked Examples Selector */}
                <div>
                  <div className="flex justify-between items-center mb-1">
                    <label className="text-xs font-semibold uppercase tracking-wider text-stone-700">
                      Worked Examples Depth
                    </label>
                    <span className="text-xs font-mono text-amber-800 font-bold uppercase">{examples}</span>
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    {(['concise', 'many'] as const).map((ex) => (
                      <button
                        key={ex}
                        type="button"
                        onClick={() => setExamples(ex)}
                        className={`py-2 px-3 text-xs font-medium rounded-lg border transition-all capitalize cursor-pointer ${
                          examples === ex
                            ? 'bg-amber-700 text-white border-amber-800 shadow-sm font-semibold'
                            : 'bg-stone-50 text-stone-700 border-stone-200 hover:bg-stone-100'
                        }`}
                      >
                        {ex === 'concise' ? 'Concise Examples' : 'In-Depth Worked Examples'}
                      </button>
                    ))}
                  </div>
                </div>

                {/* 4. Toggles */}
                <div className="flex flex-wrap gap-6 pt-1 border-t border-stone-200/80">
                  <label className="flex items-center space-x-2 cursor-pointer text-xs font-medium text-stone-800">
                    <input
                      type="checkbox"
                      checked={includeCode}
                      onChange={(e) => setIncludeCode(e.target.checked)}
                      className="rounded border-stone-300 text-amber-600 focus:ring-amber-500 w-4 h-4"
                    />
                    <span>Include Code Snippets</span>
                  </label>

                  <label className="flex items-center space-x-2 cursor-pointer text-xs font-medium text-stone-800">
                    <input
                      type="checkbox"
                      checked={detailedMath}
                      onChange={(e) => setDetailedMath(e.target.checked)}
                      className="rounded border-stone-300 text-amber-600 focus:ring-amber-500 w-4 h-4"
                    />
                    <span>Include Detailed Math Formulas (LaTeX)</span>
                  </label>
                </div>
              </div>
            )}
          </div>

          <Button
            type="submit"
            variant="primary"
            size="lg"
            className="w-full font-semibold text-stone-100 bg-stone-900 hover:bg-stone-800 py-3 shadow-md cursor-pointer"
          >
            ⚡ Synthesize Complete A4 Notes
          </Button>
        </form>
      </div>
    </MainLayout>
  );
};

export const AppRoutes: React.FC = () => {
  return (
    <Routes>
      <Route path="/" element={<HomePage />} />
      <Route path="/sidepanel" element={<SidePanelPage />} />
      <Route path="/notes" element={<NotesPage />} />
      <Route path="/notes/:id" element={<NotePage />} />
      <Route path="*" element={<HomePage />} />
    </Routes>
  );
};

export default AppRoutes;
