import { marked } from "marked";
import DOMPurify from "dompurify";

// Configure marked options
marked.setOptions({
  gfm: true,
  breaks: true,
});

export function isHtmlContent(content: string): boolean {
  if (!content) return false;
  const trimmed = content.trim();
  // Legacy full HTML documents generated by previous versions
  return (
    trimmed.startsWith("<article") ||
    (trimmed.startsWith("<div") && (trimmed.includes('class="note-content"') || trimmed.includes("class='note-content'"))) ||
    (trimmed.includes("<section") && trimmed.includes("</h2>") && !trimmed.includes("## 1."))
  );
}

export function repairMermaidDiagram(source: string): string {
  if (!source) return "";
  let diagram = source.trim();

  // 1. Decode any HTML entities (&gt;, &lt;, &amp;, &quot;, &#39;)
  diagram = diagram
    .replace(/&gt;/g, '>')
    .replace(/&lt;/g, '<')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");

  // 2. Strip code fences if present
  diagram = diagram.replace(/^```(?:mermaid)?\s*/i, '').replace(/```\s*$/i, '').trim();

  // 3. Ensure valid diagram header
  const headerMatch = diagram.match(/^(graph|flowchart|sequenceDiagram|classDiagram|stateDiagram(?:-v2)?|erDiagram|gantt|pie|gitGraph|mindmap|quadrantChart|journey|sankey-beta)\b/i);
  if (!headerMatch) {
    diagram = `graph TD\n${diagram}`;
  } else {
    diagram = diagram.replace(/^(graph|flowchart)\s+([a-z]{2})\b/i, (_, type, dir) => `${type} ${dir.toUpperCase()}`);
  }

  // 4. Fix reserved keywords and auto-quote labels
  const reservedWords = ['end', 'node', 'graph', 'subgraph', 'linkStyle', 'style', 'class', 'default', 'click', 'callback'];
  const lines = diagram.split('\n');
  let openSubgraphs = 0;

  const fixedLines = lines.map((line) => {
    let l = line;
    const trimmed = l.trim();

    if (/^subgraph\s+/i.test(trimmed)) {
      openSubgraphs++;
      const sgMatch = trimmed.match(/^subgraph\s+([A-Za-z0-9_]+)?\s*\[?"?([^"\]\n]+)"?\]?/i);
      if (sgMatch) {
        const id = sgMatch[1] || `sg_${Math.random().toString(36).substring(2, 6)}`;
        const title = sgMatch[2] || id;
        return `  subgraph ${id} ["${title.replace(/"/g, "'")}"]`;
      }
      return l;
    }

    if (trimmed === 'end') {
      openSubgraphs = Math.max(0, openSubgraphs - 1);
      return l;
    }

    if (trimmed.startsWith('%%') || /^(graph|flowchart|sequenceDiagram|classDiagram|stateDiagram)/i.test(trimmed)) {
      return l;
    }

    // Replace reserved words used as node IDs
    reservedWords.forEach((word) => {
      l = l.replace(new RegExp(`(^|\\s)(${word})(?=\\s*(\\[|\\(|\\{|\\>|---|-->|-\\.-|==>))`, 'g'), `$1${word}_node`);
      l = l.replace(new RegExp(`(-->|---|-.->|==>|\\|[^\\|]+\\|\\s*)(${word})(?=\\s*(\\[|\\(|\\{|\\s|$))`, 'g'), `$1$2_node`);
    });

    // Auto-quote all Mermaid node shapes:
    // Cylinder: id[("Label")]
    l = l.replace(/([\w-]+)\[\(\s*"?([^"\]\n]+?)"?\s*\)\]/g, '$1[("$2")]');
    // Stadium: id(["Label"])
    l = l.replace(/([\w-]+)\(\[\s*"?([^"\]\n]+?)"?\s*\]\)/g, '$1(["$2"])');
    // Hexagon: id{{"Label"}}
    l = l.replace(/([\w-]+)\{\{\s*"?([^"\}\n]+?)"?\s*\}\}/g, '$1{{"$2"}}');
    // Subroutine: id[["Label"]]
    l = l.replace(/([\w-]+)\[\[\s*"?([^"\]\n]+?)"?\s*\]\]/g, '$1[["$2"]]');
    // Decision / Rhombus: id{"Label"}
    l = l.replace(/([\w-]+)\{\s*"?([^"\}\n]+?)"?\s*\}/g, '$1{"$2"}');
    // Circle: id(("Label"))
    l = l.replace(/([\w-]+)\(\(\s*"?([^"\)\n]+?)"?\s*\)\)/g, '$1(("$2"))');
    // Standard Square: id["Label"]
    l = l.replace(/([\w-]+)\[\s*"?([^"\]\n]+?)"?\s*\]/g, (_m, id, label) => {
      if (label.startsWith('(') && label.endsWith(')')) return _m;
      if (label.startsWith('[') && label.endsWith(']')) return _m;
      return `${id}["${label.replace(/"/g, "'")}"]`;
    });
    // Standard Round / Parens: id("Label")
    l = l.replace(/([\w-]+)\(\s*"?([^"\)\n]+?)"?\s*\)/g, (_m, id, label) => {
      if (label.startsWith('[') && label.endsWith(']')) return _m;
      if (label.startsWith('(') && label.endsWith(')')) return _m;
      return `${id}("${label.replace(/"/g, "'")}")`;
    });

    // Clean pipe edge labels: A -->|Label| B -> A -->|"Label"| B
    l = l.replace(/\|([^\|\n]+)\|/g, (_m, edgeLabel) => {
      const cleanEdge = edgeLabel.trim().replace(/"/g, "'");
      return `|"${cleanEdge}"|`;
    });

    return l;
  });

  while (openSubgraphs > 0) {
    fixedLines.push('end');
    openSubgraphs--;
  }

  return fixedLines.join('\n');
}

export function healMarkdownDefects(markdown: string): string {
  if (!markdown) return "";
  let text = markdown;

  // 1. Auto-repair SQL/Database queries mistakenly enclosed in LaTeX $$ ... $$ or $ ... $
  text = text.replace(/\$\$\s*(SELECT|INSERT|UPDATE|DELETE|CREATE\s+TABLE|ALTER\s+TABLE|DROP\s+TABLE|WITH\s+[A-Za-z0-9_]+\s+AS)[\s\S]*?\$\$/gi, (match) => {
    const rawSql = match.replace(/^\$\$\s*/, "").replace(/\s*\$\$$/, "").trim();
    return `\n\`\`\`sql\n${rawSql}\n\`\`\`\n`;
  });

  text = text.replace(/\$(SELECT\s+[^$\n]+FROM[^$\n]+)\$/gi, (_match, sql) => {
    return `\`${sql.trim()}\``;
  });

  // 2. Escape isolated currency dollar amounts (e.g., "$50" or "$100/mo") to prevent accidental math mode across paragraphs
  text = text.replace(/(^|\s)\$(\d+(?:\.\d{1,2})?)(?=\s|[.,;!?\/\)]|$)/g, '$1\\$$2');

  // 3. Auto-repair Mermaid diagrams using comprehensive syntax healer
  text = text.replace(/```mermaid\s*([\s\S]*?)```/gi, (_match, diagramBody) => {
    const fixed = repairMermaidDiagram(diagramBody);
    return `\`\`\`mermaid\n${fixed}\n\`\`\``;
  });

  // 4. Strip unwanted horizontal dividing lines (---, ***, ___)
  text = text.replace(/^[ \t]*[-*_]{3,}[ \t]*$/gm, '');

  // 5. Auto-repair LaTeX equation defects (unescaped underscores inside \text{}, unescaped %, missing subscript markers)
  // Repair display math $$ ... $$
  text = text.replace(/\$\$([\s\S]*?)\$\$/g, (_match, mathContent) => {
    let repaired = mathContent;
    // Replace unescaped underscores inside \text{...}, \mathrm{...}, \mathbf{...}, \mathit{...}
    repaired = repaired.replace(/\\(text|mathrm|mathbf|mathit)\{([^{}]+)\}/g, (_m: string, cmd: string, inner: string) => {
      return `\\${cmd}{${inner.replace(/(?<!\\)_/g, '\\_')}}`;
    });
    // Replace isolated unescaped percent signs (e.g., 99.9% -> 99.9\%)
    repaired = repaired.replace(/(\d+(?:\.\d+)?)\s*%(?!\w)/g, '$1\\%');
    // Fix missing subscript operator before text block, e.g., \text{QPS} {\text{read_peak}} -> \text{QPS}_{\text{read\_peak}}
    repaired = repaired.replace(/(\\text\{[^{}]+\})\s+(\{\\text\{[^{}]+\})/g, '$1_$2');
    return `$$${repaired}$$`;
  });

  // Repair inline math $ ... $
  text = text.replace(/(?<!\\)\$([^\$\n]+?)(?<!\\)\$/g, (_match, mathContent) => {
    let repaired = mathContent;
    // Replace unescaped underscores inside \text{...}, \mathrm{...}
    repaired = repaired.replace(/\\(text|mathrm|mathbf|mathit)\{([^{}]+)\}/g, (_m: string, cmd: string, inner: string) => {
      return `\\${cmd}{${inner.replace(/(?<!\\)_/g, '\\_')}}`;
    });
    // Replace isolated unescaped percent signs
    repaired = repaired.replace(/(\d+(?:\.\d+)?)\s*%(?!\w)/g, '$1\\%');
    return `$${repaired}$`;
  });

  return text;
}

export function parseMarkdownToHtml(content: string): string {
  if (!content) return "";

  // If already legacy full HTML, sanitize, transform mermaid if present, and return
  if (isHtmlContent(content)) {
    let processedHtml = content;
    processedHtml = processedHtml.replace(
      /<pre><code class="language-mermaid">([\s\S]*?)<\/code><\/pre>/gi,
      '<div class="mermaid">$1</div>'
    );
    return DOMPurify.sanitize(processedHtml, {
      ADD_TAGS: [
        "article", "section", "header", "main", "table", "thead", "tbody", "tr", "th", "td",
        "div", "span", "p", "h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "li", "strong",
        "b", "em", "i", "blockquote", "code", "pre", "a", "br", "hr", "svg", "g", "path", "rect", "circle", "text", "line"
      ],
      ADD_ATTR: ["class", "id", "target", "rel", "href", "style", "viewBox", "width", "height", "d", "fill", "stroke", "stroke-width"],
    });
  }

  // Pre-process and heal common markdown / LaTeX / Mermaid syntax defects
  let processedMarkdown = healMarkdownDefects(content);

  // If the markdown starts with a single top-level heading '# Title' and does not already have a note-cover header,
  // gracefully transform it into a full A4 cover page
  if (/^#\s+([^#\n]+)/.test(processedMarkdown.trim()) && !processedMarkdown.includes('class="note-cover"')) {
    processedMarkdown = processedMarkdown.replace(
      /^#\s+([^\n]+)/m,
      `<header class="note-cover">
  <h1>$1</h1>
  <p class="subtitle">Complete Technical Study Guide & Architecture Whitepaper</p>
  <p class="description">Academic synthesis and technical lecture breakdown.</p>
  <div class="badge-pill">Academic Synthesis Edition  •  A4 Whitepaper</div>
</header>\n`
    );
  }

  // Convert standard markdown to HTML
  let parsedHtml = marked.parse(processedMarkdown) as string;

  // Transform blockquotes with specific labels into whitepaper styled callout cards
  parsedHtml = parsedHtml.replace(
    /<blockquote>\s*<p>\s*<strong>(Key Takeaway|Core Invariant|Summary):?<\/strong>([\s\S]*?)<\/p>\s*<\/blockquote>/gi,
    '<div class="callout takeaway"><strong>✓ $1:</strong><p>$2</p></div>'
  );

  parsedHtml = parsedHtml.replace(
    /<blockquote>\s*<p>\s*<strong>(Worked Analogy|Analogy|Mental Model):?<\/strong>([\s\S]*?)<\/p>\s*<\/blockquote>/gi,
    '<div class="callout analogy"><strong>💡 $1:</strong><p>$2</p></div>'
  );

  parsedHtml = parsedHtml.replace(
    /<blockquote>\s*<p>\s*<strong>(Worked Example|Example|Calculation):?<\/strong>([\s\S]*?)<\/p>\s*<\/blockquote>/gi,
    '<div class="callout example"><strong>📐 $1:</strong><p>$2</p></div>'
  );

  parsedHtml = parsedHtml.replace(
    /<blockquote>\s*<p>\s*<strong>(Important Warning|Warning|Caution|Pitfall):?<\/strong>([\s\S]*?)<\/p>\s*<\/blockquote>/gi,
    '<div class="callout warning"><strong>⚠ $1:</strong><p>$2</p></div>'
  );

  // Convert ```mermaid code blocks to <div class="mermaid">
  parsedHtml = parsedHtml.replace(
    /<pre><code class="language-mermaid">([\s\S]*?)<\/code><\/pre>/gi,
    '<div class="mermaid">$1</div>'
  );

  // Sanitize final output
  return DOMPurify.sanitize(parsedHtml, {
    ADD_TAGS: [
      "article", "section", "header", "main", "table", "thead", "tbody", "tr", "th", "td",
      "div", "span", "p", "h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "li", "strong",
      "b", "em", "i", "blockquote", "code", "pre", "a", "br", "hr",
      "svg", "g", "path", "rect", "circle", "text", "line", "polygon", "polyline", "marker", "foreignObject"
    ],
    ADD_ATTR: ["class", "id", "target", "rel", "href", "viewBox", "width", "height", "d", "fill", "stroke", "stroke-width", "transform", "style", "marker-end", "marker-start"],
  });
}

export function extractMarkdownHeadings(content: string): Array<{ id: string; text: string; level: number }> {
  if (!content) return [];

  if (isHtmlContent(content)) {
    const documentFragment = new DOMParser().parseFromString(content, "text/html");
    return Array.from(documentFragment.querySelectorAll("h2, h3")).map((element, index) => ({
      id: element.id || `section-${index + 1}`,
      text: element.textContent?.trim() || `Section ${index + 1}`,
      level: parseInt(element.tagName.replace("H", ""), 10),
    }));
  }

  const headings: Array<{ id: string; text: string; level: number }> = [];
  const lines = content.split("\n");
  let index = 1;

  for (const line of lines) {
    const match = line.match(/^(#{2,3})\s+(.*)$/);
    if (match) {
      const level = match[1].length;
      const text = match[2].trim().replace(/\*\*/g, "").replace(/\*/g, "");
      headings.push({
        id: `section-${index++}`,
        text,
        level,
      });
    }
  }

  return headings;
}
