import { marked } from "marked";
import DOMPurify from "dompurify";

// Configure marked options
marked.setOptions({
  gfm: true,
  breaks: true,
});

export function isHtmlContent(content: string): boolean {
  if (!content) return false;
  const trimmed = content.trim();
  // Legacy full HTML documents generated by previous versions
  return (
    trimmed.startsWith("<article") ||
    (trimmed.startsWith("<div") && (trimmed.includes('class="note-content"') || trimmed.includes("class='note-content'"))) ||
    (trimmed.includes("<section") && trimmed.includes("</h2>") && !trimmed.includes("## 1."))
  );
}

export function healMarkdownDefects(markdown: string): string {
  if (!markdown) return "";
  let text = markdown;

  // 1. Auto-repair SQL/Database queries mistakenly enclosed in LaTeX $$ ... $$ or $ ... $
  text = text.replace(/\$\$\s*(SELECT|INSERT|UPDATE|DELETE|CREATE\s+TABLE|ALTER\s+TABLE|DROP\s+TABLE|WITH\s+[A-Za-z0-9_]+\s+AS)[\s\S]*?\$\$/gi, (match) => {
    const rawSql = match.replace(/^\$\$\s*/, "").replace(/\s*\$\$$/, "").trim();
    return `\n\`\`\`sql\n${rawSql}\n\`\`\`\n`;
  });

  text = text.replace(/\$(SELECT\s+[^$\n]+FROM[^$\n]+)\$/gi, (_match, sql) => {
    return `\`${sql.trim()}\``;
  });

  // 2. Escape isolated currency dollar amounts (e.g., "$50" or "$100/mo") to prevent accidental math mode across paragraphs
  text = text.replace(/(^|\s)\$(\d+(?:\.\d{1,2})?)(?=\s|[.,;!?\/\)]|$)/g, '$1\\$$2');

  // 3. Auto-repair Mermaid diagrams: quote unquoted node labels with parentheses, colons, or slashes
  text = text.replace(/```mermaid\s*([\s\S]*?)```/gi, (_match, diagramBody) => {
    const lines = diagramBody.split('\n');
    const fixedLines = lines.map((line: string) => {
      // If line is a node declaration with unquoted parens, colons, or slashes: A[Client (React)] -> A["Client (React)"]
      return line.replace(/([A-Za-z0-9_]+)\[([^"\]\n]+[\(:/][^"\]\n]*)\]/g, '$1["$2"]');
    });
    return `\`\`\`mermaid\n${fixedLines.join('\n')}\n\`\`\``;
  });

  // 4. Strip unwanted horizontal dividing lines (---, ***, ___)
  text = text.replace(/^[ \t]*[-*_]{3,}[ \t]*$/gm, '');

  return text;
}

export function parseMarkdownToHtml(content: string): string {
  if (!content) return "";

  // If already legacy full HTML, sanitize, transform mermaid if present, and return
  if (isHtmlContent(content)) {
    let processedHtml = content;
    processedHtml = processedHtml.replace(
      /<pre><code class="language-mermaid">([\s\S]*?)<\/code><\/pre>/gi,
      '<div class="mermaid">$1</div>'
    );
    return DOMPurify.sanitize(processedHtml, {
      ADD_TAGS: [
        "article", "section", "header", "main", "table", "thead", "tbody", "tr", "th", "td",
        "div", "span", "p", "h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "li", "strong",
        "b", "em", "i", "blockquote", "code", "pre", "a", "br", "hr", "svg", "g", "path", "rect", "circle", "text", "line"
      ],
      ADD_ATTR: ["class", "id", "target", "rel", "href", "style", "viewBox", "width", "height", "d", "fill", "stroke", "stroke-width"],
    });
  }

  // Pre-process and heal common markdown / LaTeX / Mermaid syntax defects
  let processedMarkdown = healMarkdownDefects(content);

  // If the markdown starts with a single top-level heading '# Title' and does not already have a note-cover header,
  // gracefully transform it into a full A4 cover page
  if (/^#\s+([^#\n]+)/.test(processedMarkdown.trim()) && !processedMarkdown.includes('class="note-cover"')) {
    processedMarkdown = processedMarkdown.replace(
      /^#\s+([^\n]+)/m,
      `<header class="note-cover">
  <h1>$1</h1>
  <p class="subtitle">Complete Technical Study Guide & Architecture Whitepaper</p>
  <p class="description">Academic synthesis and technical lecture breakdown.</p>
  <div class="badge-pill">Academic Synthesis Edition  •  A4 Whitepaper</div>
</header>\n`
    );
  }

  // Convert standard markdown to HTML
  let parsedHtml = marked.parse(processedMarkdown) as string;

  // Transform blockquotes with specific labels into whitepaper styled callout cards
  parsedHtml = parsedHtml.replace(
    /<blockquote>\s*<p>\s*<strong>(Key Takeaway|Core Invariant|Summary):?<\/strong>([\s\S]*?)<\/p>\s*<\/blockquote>/gi,
    '<div class="callout takeaway"><strong>✓ $1:</strong><p>$2</p></div>'
  );

  parsedHtml = parsedHtml.replace(
    /<blockquote>\s*<p>\s*<strong>(Worked Analogy|Analogy|Mental Model):?<\/strong>([\s\S]*?)<\/p>\s*<\/blockquote>/gi,
    '<div class="callout analogy"><strong>💡 $1:</strong><p>$2</p></div>'
  );

  parsedHtml = parsedHtml.replace(
    /<blockquote>\s*<p>\s*<strong>(Worked Example|Example|Calculation):?<\/strong>([\s\S]*?)<\/p>\s*<\/blockquote>/gi,
    '<div class="callout example"><strong>📐 $1:</strong><p>$2</p></div>'
  );

  parsedHtml = parsedHtml.replace(
    /<blockquote>\s*<p>\s*<strong>(Important Warning|Warning|Caution|Pitfall):?<\/strong>([\s\S]*?)<\/p>\s*<\/blockquote>/gi,
    '<div class="callout warning"><strong>⚠ $1:</strong><p>$2</p></div>'
  );

  // Convert ```mermaid code blocks to <div class="mermaid">
  parsedHtml = parsedHtml.replace(
    /<pre><code class="language-mermaid">([\s\S]*?)<\/code><\/pre>/gi,
    '<div class="mermaid">$1</div>'
  );

  // Sanitize final output
  return DOMPurify.sanitize(parsedHtml, {
    ADD_TAGS: [
      "article", "section", "header", "main", "table", "thead", "tbody", "tr", "th", "td",
      "div", "span", "p", "h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "li", "strong",
      "b", "em", "i", "blockquote", "code", "pre", "a", "br", "hr",
      "svg", "g", "path", "rect", "circle", "text", "line", "polygon", "polyline", "marker", "foreignObject"
    ],
    ADD_ATTR: ["class", "id", "target", "rel", "href", "viewBox", "width", "height", "d", "fill", "stroke", "stroke-width", "transform", "style", "marker-end", "marker-start"],
  });
}

export function extractMarkdownHeadings(content: string): Array<{ id: string; text: string; level: number }> {
  if (!content) return [];

  if (isHtmlContent(content)) {
    const documentFragment = new DOMParser().parseFromString(content, "text/html");
    return Array.from(documentFragment.querySelectorAll("h2, h3")).map((element, index) => ({
      id: element.id || `section-${index + 1}`,
      text: element.textContent?.trim() || `Section ${index + 1}`,
      level: parseInt(element.tagName.replace("H", ""), 10),
    }));
  }

  const headings: Array<{ id: string; text: string; level: number }> = [];
  const lines = content.split("\n");
  let index = 1;

  for (const line of lines) {
    const match = line.match(/^(#{2,3})\s+(.*)$/);
    if (match) {
      const level = match[1].length;
      const text = match[2].trim().replace(/\*\*/g, "").replace(/\*/g, "");
      headings.push({
        id: `section-${index++}`,
        text,
        level,
      });
    }
  }

  return headings;
}
